<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <None Update="settings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\cat.jpg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\404.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Steam\style.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Steam\index.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Steam\qr-code-1000-1000.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\chatgpt.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\deepseek.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\geeksforgeeks.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\github.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\linkedin.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\plus.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\index.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\search.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\search-bar.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\search2.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="static\Search\youtube.svg">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Framework\Settings\" />
    </ItemGroup>

</Project>
